version: "3.9"
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8080:8080
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID:-}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET:-}
